ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_ASSIGNMENT_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_PERMISSIONS_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ROLE_ASSIGNMENT_DEACTIVATED';

ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'MEMBERSHIP';
